### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sid8840** [Govi02/irctc_autofill_extension#1]
Can you provide steps for installation?

**Comment by Govi02** [comment]
> Can you provide steps for installation?

Sure, why not.

Installation

1) Initially, Clone/Download this repository on your system.
2) Go to chrome://extensions/ via google chrome
3) click Load unpacked on top-left and then select the downloaded repository folder.
4) Finally, Activate this extensions, then you can use it.

You can ask any doubts without any hesitation.

**Comment by brupadhyay** [comment]
gives error 
![image](https://github.com/Govi02/irctc_autofill_extension/assets/92944256/2d8103ae-7cd0-48d5-8dbd-2f318275fb26)
