### ISSUE TITLE
Captcha reloads extactly at 10:00 and 11:00

### ISSUE THREAD

**Issue by vaishnu28** [Govi02/irctc_autofill_extension#2]
The issue is that script works flawlessly at non tatkal times. At tatkal timing i.e Exactly at 10:00 and 11;00 , when the captcha is filled and submitted , a new captcha is being generated by irctc website. I think it is because the irctc website detects the script maybe? Captcha gets auto submitted by the time I fill it.
Can you modify the script , where it stops auto detecting captcha , and only proceed when the SUBMIT button is hit by user manually?

**Comment by Govi02** [comment]
Thanks @vaishnu28 , **Now you can click SUBMIT button manually using this code**, I just wrote with auto submit stuffs in order to reduce filling time , Now it's under the control of user.
